import API_BASE_URL from './config';

const ENDPOINTS = {
  AI:{
    UPLOAD: `${API_BASE_URL}/ai/upload`,
    CLEAR: `${API_BASE_URL}/ai/clear_files`,
    CHAT: `${API_BASE_URL}/ai/chat`,
    RESET: `${API_BASE_URL}/ai/reset_session`,
  },
  NOTEBOOKS: {
    LIST: (createdBy, spaceType) => `${API_BASE_URL}/notebooks/list?created_by=${createdBy}&space_type=${spaceType}`,
    CREATE: `${API_BASE_URL}/notebooks/create`,
    UPDATE: (id) => `${API_BASE_URL}/notebooks/${id}`,
    DELETE: (id) => `${API_BASE_URL}/notebooks/${id}`,
    FETCH_COLLABORATORS: (id) => `${API_BASE_URL}/notebooks/${id}/collaborators`,
    ADD_COLLABORATOR: (id) => `${API_BASE_URL}/notebooks/${id}/add-collaborator`,
    REMOVE_COLLABORATOR: (notebookId, userId) => `${API_BASE_URL}/notebooks/${notebookId}/collaborator/${userId}`,
  },
  NOTES: {
    CREATE: `${API_BASE_URL}/notes/create`,
    LIST: (notebookId) => `${API_BASE_URL}/notes/list/${notebookId}`,
    GET: (noteId) => `${API_BASE_URL}/notes/${noteId}`,
    UPDATE: (noteId) => `${API_BASE_URL}/notes/${noteId}`,
    DELETE: (noteId) => `${API_BASE_URL}/notes/${noteId}`,
    COPY: (noteId) => `${API_BASE_URL}/notes/${noteId}/copy`,
    LOCK: (noteId) => `${API_BASE_URL}/notes/${noteId}/lock`,
    UNLOCK: (noteId) => `${API_BASE_URL}/notes/${noteId}/unlock`,
    LOCK_STATUS: (noteId) => `${API_BASE_URL}/notes/${noteId}/lock-status`,
    UPDATE_POSITION: (noteId) => `${API_BASE_URL}/notes/${noteId}/position`,
    TOGGLE_PIN: (noteId) => `${API_BASE_URL}/notes/${noteId}/pin`,
  },
  TESTS: {
    LIST: (notebookId, userId) => `${API_BASE_URL}/tests/list?user_id=${userId}&notebook_id=${notebookId}`,
    GENERATE: `${API_BASE_URL}/tests/generate`,
    GENERATE_FROM_FILE: `${API_BASE_URL}/tests/generate-from-file`,
    GET: (testId) => `${API_BASE_URL}/tests/${testId}`,
    DELETE: (testId, userId) => `${API_BASE_URL}/tests/${testId}?user_id=${userId}`,
    SUBMIT_ANSWER: `${API_BASE_URL}/tests/submit-answer`,
    RESULTS: (testId, userId) => `${API_BASE_URL}/tests/results/${testId}?user_id=${userId}`,
    TOGGLE_PIN: (testId) => `${API_BASE_URL}/tests/${testId}/pin`,
    UPDATE_POSITION: (testId) => `${API_BASE_URL}/tests/${testId}/position`,
    COPY: (testId) => `${API_BASE_URL}/tests/${testId}/copy`,
    NOTES: {
      LIST: (notebookId) => `${API_BASE_URL}/notes/list/${notebookId}`,
    },
  },
  FLASHCARDS: {
    LIST: (notebookId) => `${API_BASE_URL}/flashcards/sets/${notebookId}`,
    GENERATE: `${API_BASE_URL}/flashcards/generate`,
    GENERATE_FROM_FILE: `${API_BASE_URL}/flashcards/generate-from-file`,
    GET_CARDS: (setId) => `${API_BASE_URL}/flashcards/set/${setId}/cards`,
    UPDATE_SET: (setId) => `${API_BASE_URL}/flashcards/set/${setId}`,
    DELETE_SET: (setId) => `${API_BASE_URL}/flashcards/set/${setId}`,
    REVIEW: `${API_BASE_URL}/flashcards/review`,
    REORDER: `${API_BASE_URL}/flashcards/reorder`,
    TOGGLE_PIN: (setId) => `${API_BASE_URL}/flashcards/set/${setId}/pin`,
    UPDATE_POSITION: (setId) => `${API_BASE_URL}/flashcards/set/${setId}/position`,
    PROGRESS: (userId, setId) => `${API_BASE_URL}/flashcards/progress/${userId}/${setId}`,
    COPY_SET: (setId) => `${API_BASE_URL}/flashcards/set/${setId}/copy`,
    CARDS: {
      CREATE: `${API_BASE_URL}/flashcards/card`,
      UPDATE: (cardId) => `${API_BASE_URL}/flashcards/card/${cardId}`,
      DELETE: (cardId) => `${API_BASE_URL}/flashcards/card/${cardId}`,
    },
  },
  FOLDERS: {
    NOTES: {
      LIST: (notebookId, userId) => `${API_BASE_URL}/folders/notes/list?user_id=${userId}&notebook_id=${notebookId}`,
      CREATE: `${API_BASE_URL}/folders/notes/create`,
      DELETE: (folderId) => `${API_BASE_URL}/folders/notes/${folderId}`,
      RENAME: (folderId) => `${API_BASE_URL}/folders/notes/${folderId}/rename`,
      MOVE: (folderId) => `${API_BASE_URL}/folders/notes/${folderId}/move`,
      MOVE_ITEM: `${API_BASE_URL}/folders/notes/move-item`,
      UPDATE_POSITION: (folderId) => `${API_BASE_URL}/folders/notes/${folderId}/position`,
      COPY: (folderId) => `${API_BASE_URL}/folders/notes/${folderId}/copy`,
    },
    TESTS: {
      LIST: (notebookId, userId) => `${API_BASE_URL}/folders/tests/list?user_id=${userId}&notebook_id=${notebookId}`,
      CREATE: `${API_BASE_URL}/folders/tests/create`,
      DELETE: (folderId) => `${API_BASE_URL}/folders/tests/${folderId}`,
      RENAME: (folderId) => `${API_BASE_URL}/folders/tests/${folderId}/rename`,
      MOVE: (folderId) => `${API_BASE_URL}/folders/tests/${folderId}/move`,
      MOVE_ITEM: `${API_BASE_URL}/folders/tests/move-item`,
      UPDATE_POSITION: (folderId) => `${API_BASE_URL}/folders/tests/${folderId}/position`,
      COPY: (folderId) => `${API_BASE_URL}/folders/tests/${folderId}/copy`,
    },
    FLASHCARDS: {
      LIST: (notebookId, userId) => `${API_BASE_URL}/folders/flashcards/list?user_id=${userId}&notebook_id=${notebookId}`,
      CREATE: `${API_BASE_URL}/folders/flashcards/create`,
      DELETE: (folderId) => `${API_BASE_URL}/folders/flashcards/${folderId}`,
      RENAME: (folderId) => `${API_BASE_URL}/folders/flashcards/${folderId}/rename`,
      MOVE: (folderId) => `${API_BASE_URL}/folders/flashcards/${folderId}/move`,
      MOVE_ITEM: `${API_BASE_URL}/folders/flashcards/move-item`,
      UPDATE_POSITION: (folderId) => `${API_BASE_URL}/folders/flashcards/${folderId}/position`,
      COPY: (folderId) => `${API_BASE_URL}/folders/flashcards/${folderId}/copy`,
    },
    PODCASTS: {
      LIST: (notebookId, userId) => `${API_BASE_URL}/podcasts/folders/list?user_id=${userId}&notebook_id=${notebookId}`,
      CREATE: `${API_BASE_URL}/podcasts/folders/create`,
      DELETE: (folderId) => `${API_BASE_URL}/podcasts/folders/${folderId}`,
      RENAME: (folderId) => `${API_BASE_URL}/podcasts/folders/${folderId}/rename`,
      MOVE: (folderId) => `${API_BASE_URL}/podcasts/folders/${folderId}/move`,
      MOVE_ITEM: `${API_BASE_URL}/podcasts/folders/move-item`,
      UPDATE_POSITION: (folderId) => `${API_BASE_URL}/podcasts/folders/${folderId}/position`,
      COPY: (folderId) => `${API_BASE_URL}/podcasts/folders/${folderId}/copy`,
    },
  },
  PODCASTS: {
    LIST: (notebookId) => `${API_BASE_URL}/podcasts/list?notebook_id=${notebookId}`,
    GENERATE: `${API_BASE_URL}/podcasts/generate`,
    DELETE: (podcastId) => `${API_BASE_URL}/podcasts/${podcastId}`,
    RENAME: (podcastId) => `${API_BASE_URL}/podcasts/${podcastId}/rename`,
    TOGGLE_PIN: (podcastId) => `${API_BASE_URL}/podcasts/${podcastId}/pin`,
    UPDATE_POSITION: (podcastId) => `${API_BASE_URL}/podcasts/${podcastId}/position`,
    COPY: (podcastId) => `${API_BASE_URL}/podcasts/${podcastId}/copy`,
  },
  USERS: {
    LOGIN: `${API_BASE_URL}/auth/login`,
    LOGOUT: `${API_BASE_URL}/auth/logout`,
    GET_CURRENT: `${API_BASE_URL}/user/`,
    CHANGE_USERNAME: (username) => `${API_BASE_URL}/user/username/${username}`,
    CHECK_AVAILABILITY: (username) => `${API_BASE_URL}/user/check-availability/${username}`,
    REQUEST_PASSWORD_RESET: `${API_BASE_URL}/auth/forgot-password`, // Monika tego endpointa uzyj
    CHANGE_PASSWORD: `${API_BASE_URL}/user/password`, // ja to tu daje, gdyz ja mam tez u siebie zmiane hasla przez maila
    UPLOAD_AVATAR: `${API_BASE_URL}/user/avatar`,
    DELETE_AVATAR: `${API_BASE_URL}/user/avatar`,
    DELETE_ACCOUNT: `${API_BASE_URL}/user/delete-account`,
    GET_AVATAR: (avatarPath) => avatarPath ? `${API_BASE_URL}${avatarPath}` : null,
    COMPLETE_TUTORIAL: `${API_BASE_URL}/user/complete-tutorial`,
  },
  AUTH: {
    REGISTER: `${API_BASE_URL}/auth/`,
    LOGIN: `${API_BASE_URL}/auth/token`,
    FORGOT_PASSWORD: `${API_BASE_URL}/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE_URL}/auth/reset-password`,
  },
  GROUP_CHAT: {
    HISTORY: (notebookId) => `${API_BASE_URL}/group-chat/${notebookId}/history`,
    MEMBERS: (notebookId) => `${API_BASE_URL}/group-chat/${notebookId}/members`,
    PINNED: (notebookId) => `${API_BASE_URL}/group-chat/${notebookId}/pinned`,
    UNPIN_ALL: (notebookId) => `${API_BASE_URL}/group-chat/${notebookId}/unpin`,
    
    DELETE_MESSAGE: (messageId, userId) => `${API_BASE_URL}/group-chat/message/${messageId}?user_id=${userId}`,
    EDIT_MESSAGE: (messageId, userId, content) => 
        `${API_BASE_URL}/group-chat/message/${messageId}?user_id=${userId}&new_content=${encodeURIComponent(content)}`,
    PIN_MESSAGE: (messageId, userId) => `${API_BASE_URL}/group-chat/message/${messageId}/pin?user_id=${userId}`,

    RESOURCES: {
      NOTES: (notebookId) => `${API_BASE_URL}/group-chat/notes/notebook/${notebookId}`,
      TESTS: (notebookId) => `${API_BASE_URL}/group-chat/tests/notebook/${notebookId}`,
      FLASHCARDS: (notebookId) => `${API_BASE_URL}/group-chat/flashcards/notebook/${notebookId}`,
      PODCASTS: (notebookId) => `${API_BASE_URL}/group-chat/podcasts/notebook/${notebookId}`,
    }
  },
  NOTIFICATIONS: {
    LIST: (userId) => `${API_BASE_URL}/notifications/${userId}`,
    MARK_READ: (notifId) => `${API_BASE_URL}/notifications/${notifId}/read`,
    DELETE: (notifId) => `${API_BASE_URL}/notifications/${notifId}`,
    CLEAR_ALL: (userId) => `${API_BASE_URL}/notifications/user/${userId}/all`,
  },
  FILES: {
    UPLOAD: `${API_BASE_URL}/files/upload`,
    LIST: (notebookId) => `${API_BASE_URL}/files/list/${notebookId}`,
    DELETE: (fileId) => `${API_BASE_URL}/files/${fileId}`,
  },
  CONTACT: {
    SUBMIT: `${API_BASE_URL}/contact/`,
  },
};

export default ENDPOINTS;