"""Add has_completed_tutorial field to users table

Revision ID: 15eeedf1c300
Revises: 12484a004059
Create Date: 2026-01-10 12:16:54.248767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15eeedf1c300'
down_revision: Union[str, None] = '12484a004059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_tutorial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_tutorial')
    # ### end Alembic commands ###
