"""relations between notebook and notes changed

Revision ID: 177c9b7f8f88
Revises: 6748d762c0dd
Create Date: 2025-10-18 23:40:52.801862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177c9b7f8f88'
down_revision: Union[str, None] = '6748d762c0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spaces_id', table_name='spaces')
    op.drop_table('spaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='spaces_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='spaces_pkey'),
    sa.UniqueConstraint('name', name='spaces_name_key')
    )
    op.create_index('ix_spaces_id', 'spaces', ['id'], unique=False)
    # ### end Alembic commands ###
