"""add flashcard system tables

Revision ID: 2554de3c47a9
Revises: fa455769426b
Create Date: 2025-10-27 17:06:37.388197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2554de3c47a9'
down_revision: Union[str, None] = 'fa455769426b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('total_cards', sa.Integer(), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('source_files', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_sets_id'), 'flashcard_sets', ['id'], unique=False)
    op.create_index(op.f('ix_flashcard_sets_note_id'), 'flashcard_sets', ['note_id'], unique=True)
    op.create_index(op.f('ix_flashcard_sets_notebook_id'), 'flashcard_sets', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_flashcard_sets_user_id'), 'flashcard_sets', ['user_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_reviews_flashcard_id'), 'flashcard_reviews', ['flashcard_id'], unique=False)
    op.create_index(op.f('ix_flashcard_reviews_id'), 'flashcard_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_flashcard_reviews_user_id'), 'flashcard_reviews', ['user_id'], unique=False)
    op.add_column('flashcards', sa.Column('flashcard_set_id', sa.Integer(), nullable=False))
    op.add_column('flashcards', sa.Column('position', sa.Integer(), nullable=True))
    op.alter_column('flashcards', 'question',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_index(op.f('ix_flashcards_flashcard_set_id'), 'flashcards', ['flashcard_set_id'], unique=False)
    op.create_index(op.f('ix_flashcards_position'), 'flashcards', ['position'], unique=False)
    op.drop_constraint('flashcards_note_id_fkey', 'flashcards', type_='foreignkey')
    op.drop_constraint('flashcards_user_id_fkey', 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'flashcard_sets', ['flashcard_set_id'], ['id'])
    op.drop_column('flashcards', 'note_id')
    op.drop_column('flashcards', 'user_id')
    op.drop_column('flashcards', 'is_shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('flashcards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flashcards', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key('flashcards_user_id_fkey', 'flashcards', 'users', ['user_id'], ['id'])
    op.create_foreign_key('flashcards_note_id_fkey', 'flashcards', 'notes', ['note_id'], ['id'])
    op.drop_index(op.f('ix_flashcards_position'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_flashcard_set_id'), table_name='flashcards')
    op.alter_column('flashcards', 'answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flashcards', 'question',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('flashcards', 'position')
    op.drop_column('flashcards', 'flashcard_set_id')
    op.drop_index(op.f('ix_flashcard_reviews_user_id'), table_name='flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_reviews_id'), table_name='flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_reviews_flashcard_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_sets_user_id'), table_name='flashcard_sets')
    op.drop_index(op.f('ix_flashcard_sets_notebook_id'), table_name='flashcard_sets')
    op.drop_index(op.f('ix_flashcard_sets_note_id'), table_name='flashcard_sets')
    op.drop_index(op.f('ix_flashcard_sets_id'), table_name='flashcard_sets')
    op.drop_table('flashcard_sets')
    # ### end Alembic commands ###
