"""modified notebooks table, added space_id

Revision ID: 29fccbf4ba5d
Revises: a8daf37d085b
Create Date: 2025-07-01 21:51:17.209324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29fccbf4ba5d'
down_revision: Union[str, None] = 'a8daf37d085b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('space_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notebooks', 'spaces', ['space_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.drop_column('notebooks', 'space_id')
    # ### end Alembic commands ###
