"""add is_pinned and grid_position to study_files table

Revision ID: 5656fcef2c83
Revises: b70587570eac
Create Date: 2026-01-18 11:33:44.477756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5656fcef2c83'
down_revision: Union[str, None] = 'b70587570eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_files', sa.Column('grid_position', sa.Integer(), nullable=True))
    op.add_column('study_files', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_files', 'is_pinned')
    op.drop_column('study_files', 'grid_position')
    # ### end Alembic commands ###
