"""spaces deleted and notebooks table is altered

Revision ID: 6e65e53fe388
Revises: 29fccbf4ba5d
Create Date: 2025-08-06 17:26:59.939678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e65e53fe388'
down_revision: Union[str, None] = '29fccbf4ba5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notebooks_space_id_fkey', 'notebooks', type_='foreignkey')
    op.drop_column('notebooks', 'space_id')
    op.drop_index('ix_spaces_id', table_name='spaces')
    op.drop_table('spaces')
    op.add_column('notebooks', sa.Column('space_type', sa.String(), nullable=True))
    op.add_column('notebooks', sa.Column('is_shared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('space_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notebooks_space_id_fkey', 'notebooks', 'spaces', ['space_id'], ['id'])
    op.drop_column('notebooks', 'is_shared')
    op.drop_column('notebooks', 'space_type')
    op.create_table('spaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='spaces_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='spaces_pkey'),
    sa.UniqueConstraint('name', name='spaces_name_key')
    )
    op.create_index('ix_spaces_id', 'spaces', ['id'], unique=False)
    # ### end Alembic commands ###
