"""Dodanie przypinania

Revision ID: 804f9d52a1bc
Revises: 52bb5bf55f97
Create Date: 2025-12-30 13:08:06.991507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804f9d52a1bc'
down_revision: Union[str, None] = '52bb5bf55f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook_messages', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebook_messages', 'is_pinned')
    # ### end Alembic commands ###
