"""added podcast model

Revision ID: 82b98b350815
Revises: 57147f48fba0
Create Date: 2025-12-07 00:52:46.467793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b98b350815'
down_revision: Union[str, None] = '57147f48fba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    op.alter_column('flashcard_sets', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_test_folders_id'), 'test_folders', ['id'], unique=False)
    op.alter_column('tests', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_notebook'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'notebooks', ['notebook_id'], ['id'])
    op.drop_constraint(op.f('fk_test_question'), 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'test_questions', ['test_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_test_question'), 'user_answers', 'test_questions', ['test_question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notebook'), 'tests', 'notebooks', ['notebook_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tests', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_test_folders_id'), table_name='test_folders')
    op.alter_column('flashcard_sets', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_table('podcasts')
    # ### end Alembic commands ###
