"""podcasts edited for pins and folders

Revision ID: a34e2ce0db0c
Revises: 82b98b350815
Create Date: 2025-12-15 17:27:35.826584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34e2ce0db0c'
down_revision: Union[str, None] = '82b98b350815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['podcast_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_folders_id'), 'podcast_folders', ['id'], unique=False)
    op.add_column('podcasts', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('podcasts', sa.Column('grid_position', sa.Integer(), nullable=True))
    op.add_column('podcasts', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'podcasts', 'podcast_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'podcasts', type_='foreignkey')
    op.drop_column('podcasts', 'is_pinned')
    op.drop_column('podcasts', 'grid_position')
    op.drop_column('podcasts', 'folder_id')
    op.drop_index(op.f('ix_podcast_folders_id'), table_name='podcast_folders')
    op.drop_table('podcast_folders')
    # ### end Alembic commands ###
