"""crated spacess

Revision ID: a8daf37d085b
Revises: 85b80d835ee1
Create Date: 2025-07-01 17:20:23.223146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8daf37d085b'
down_revision: Union[str, None] = '85b80d835ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_answers_test_question_id', 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'test_question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('test_question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_user_answers_test_question_id', 'user_answers', 'test_questions', ['test_question_id'], ['id'])
    # ### end Alembic commands ###
