"""nowe wiadomosci chat grupowy

Revision ID: b70587570eac
Revises: 15eeedf1c300
Create Date: 2026-01-12 15:37:41.009203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70587570eac'
down_revision: Union[str, None] = '15eeedf1c300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_read_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_read_status_id'), 'chat_read_status', ['id'], unique=False)
    op.create_index(op.f('ix_chat_read_status_notebook_id'), 'chat_read_status', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_chat_read_status_user_id'), 'chat_read_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_read_status_user_id'), table_name='chat_read_status')
    op.drop_index(op.f('ix_chat_read_status_notebook_id'), table_name='chat_read_status')
    op.drop_index(op.f('ix_chat_read_status_id'), table_name='chat_read_status')
    op.drop_table('chat_read_status')
    # ### end Alembic commands ###
