"""dodanie edytowania i usuwania wiadomosci

Revision ID: d7740af041e4
Revises: d4e0fe8b4645
Create Date: 2025-12-25 11:21:29.586155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7740af041e4'
down_revision: Union[str, None] = 'd4e0fe8b4645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook_messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('notebook_messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebook_messages', 'is_deleted')
    op.drop_column('notebook_messages', 'is_edited')
    # ### end Alembic commands ###
