"""add folder_id to study_files table

Revision ID: f761b1280100
Revises: 5656fcef2c83
Create Date: 2026-01-18 11:54:57.234660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f761b1280100'
down_revision: Union[str, None] = '5656fcef2c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_files', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_files', 'note_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_files', type_='foreignkey')
    op.drop_column('study_files', 'folder_id')
    # ### end Alembic commands ###
