"""new table notebook collabolator

Revision ID: fa455769426b
Revises: 1d25e4fec88f
Create Date: 2025-10-19 12:48:17.268103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa455769426b'
down_revision: Union[str, None] = '1d25e4fec88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_collaborators_id'), 'notebook_collaborators', ['id'], unique=False)
    op.drop_constraint('notebooks_name_key', 'notebooks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('notebooks_name_key', 'notebooks', ['name'])
    op.drop_index(op.f('ix_notebook_collaborators_id'), table_name='notebook_collaborators')
    op.drop_table('notebook_collaborators')
    # ### end Alembic commands ###
